# Generated by Django 6.0.7 on 2026-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_requested',
            field=models.BooleanField(default=False, verbose_name='درخواست پیک'),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عرض جغرافیایی (Lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='طول جغرافیایی (Lng)'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
