# Generated by Django 6.0.7 on 2026-09-14 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_courier_requested_order_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی قیمت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای قیمت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='نام خشکشویی', max_length=100, verbose_name='نام فروشگاه')),
                ('tagline', models.CharField(blank=True, default='خدمات خشکشویی و سفیدشویی پریمیوم', max_length=150, verbose_name='تگ\u200cلاین')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier_dispatched',
            field=models.BooleanField(default=False, verbose_name='پیک ارسال شد'),
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع لباس')),
                ('dry_clean_price', models.CharField(help_text='مثلاً 520,000 یا «۳ تا ۷ میلیون»', max_length=30, verbose_name='خشکشویی + اتو')),
                ('iron_only_price', models.CharField(blank=True, help_text='خالی بگذارید یعنی ---', max_length=30, null=True, verbose_name='فقط اتو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.pricecategory')),
            ],
            options={
                'verbose_name': 'قیمت خدمت',
                'verbose_name_plural': 'لیست قیمت\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
