# Generated by Django 6.0.7 on 2026-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'دریافت شده'), ('washing', 'در حال شستشو'), ('ironing', 'در حال اتوکشی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شده')], default='received', max_length=20),
        ),
    ]
