# Generated by Django 6.0.7 on 2026-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pricecategory_shopsettings_order_courier_dispatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات لباس'),
        ),
    ]
