# Generated by Django 6.0.7 on 2026-10-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='address',
            field=models.TextField(blank=True, default='تهران، بلوار فردوس غرب، بهار جنوبی (تقوی)، نبش کوچه وحید شرقی، پلاک ۵۲', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='name',
            field=models.CharField(default='خشکشویی و سفید شویی آرین', max_length=100, verbose_name='نام فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='phone',
            field=models.CharField(blank=True, default='۰۹۱۲-۳۲۷۷۸۸۱', max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='tagline',
            field=models.CharField(blank=True, default='خشکشویی و سفید شویی آرین', max_length=150, verbose_name='تگ\u200cلاین'),
        ),
    ]
