# Generated by Django 6.0.7 on 2026-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_shopsettings_address_alter_shopsettings_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='address',
            field=models.TextField(blank=True, default='تهران، ارم، بلوار فردوس غرب، خیابان بهار جنوبی', verbose_name='آدرس'),
        ),
    ]
