# Generated by Django 6.0.7 on 2026-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_shopsettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceitem',
            name='dry_clean_price',
            field=models.CharField(blank=True, default='', help_text='اگر قیمت مشخص نیست خالی بگذارید.', max_length=30, verbose_name='خشکشویی + اتو'),
        ),
    ]
