# Generated by Django 6.0.7 on 2026-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_fix_price_item_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_courier_dispatched',
            field=models.BooleanField(default=False, verbose_name='پیک تحویل ارسال شد'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_courier_requested',
            field=models.BooleanField(default=False, verbose_name='درخواست پیک (تحویل لباس)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عرض جغرافیایی تحویل (Lat)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='طول جغرافیایی تحویل (Lng)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_dispatched',
            field=models.BooleanField(default=False, verbose_name='پیک دریافت ارسال شد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier_requested',
            field=models.BooleanField(default=False, verbose_name='درخواست پیک (دریافت لباس)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عرض جغرافیایی دریافت (Lat)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='طول جغرافیایی دریافت (Lng)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی دریافت'),
        ),
    ]
