# Generated by Django 6.0.7 on 2026-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_delivery_courier_dispatched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='authority',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
