# Generated by Django 6.0.7 on 2026-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_wallettransaction_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='آدرس ثبت\u200cشده'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_latitude',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='عرض جغرافیایی آدرس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_longitude',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='طول جغرافیایی آدرس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='کد پستی آدرس'),
        ),
    ]
